(part "TLV75733PDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType POWER))
        (port "2" (symbPinId 2) (portName "GND") (portType GROUND))
        (port "3" (symbPinId 3) (portName "EN") (portType INPUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType OUTPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV75733PDBVR")
    (property "Mouser_Part_Number" "595-TLV75733PDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV75733PDBVR?qs=y6ZabgHbY%252BwAAzSntTW34w%3D%3D")
    (property "Arrow_Part_Number" "TLV75733PDBVR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tlv75733pdbvr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "LDO Voltage Regulators 1A Low-IQ Small-Size Low-Dropout (LDO) Regulator 5-SOT-23 -40 to 125")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tlv757p")
    (property "symbolName1" "TLV75733PDBVR")
)
