(part "ICE5LP2K-SG48ITR"
    (packageRef "QFN50P700X700X100-49N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VCCIO_2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IOB_6A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IOB_9B") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IOB_8A") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VCC_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IOB_13B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CDONE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CRESET_B") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IOB_16A") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IOB_18A") (portType INOUT))
        (port "11" (symbPinId 11) (portName "IOB_20A") (portType INOUT))
        (port "12" (symbPinId 12) (portName "IOB_22A") (portType INOUT))
        (port "13" (symbPinId 13) (portName "IOB_24A") (portType INOUT))
        (port "14" (symbPinId 14) (portName "IOB_32A_SPI_SO") (portType INOUT))
        (port "15" (symbPinId 15) (portName "IOB_34A_SPI_SCK") (portType INOUT))
        (port "16" (symbPinId 16) (portName "IOB_35B_SPI_SS") (portType INOUT))
        (port "17" (symbPinId 17) (portName "IOB_33B_SPI_SI") (portType INOUT))
        (port "18" (symbPinId 18) (portName "IOB_31B") (portType INOUT))
        (port "19" (symbPinId 19) (portName "IOB_29B") (portType INOUT))
        (port "20" (symbPinId 20) (portName "IOB_25B_G3") (portType INOUT))
        (port "21" (symbPinId 21) (portName "IOB_23B") (portType INOUT))
        (port "22" (symbPinId 22) (portName "SPI_VCCIO1") (portType INOUT))
        (port "23" (symbPinId 23) (portName "IOT_37A") (portType INOUT))
        (port "24" (symbPinId 24) (portName "VPP_2V5") (portType INOUT))
        (port "25" (symbPinId 25) (portName "IOT_36B") (portType INOUT))
        (port "26" (symbPinId 26) (portName "IOT_39A") (portType INOUT))
        (port "27" (symbPinId 27) (portName "IOT_38B") (portType INOUT))
        (port "28" (symbPinId 28) (portName "IOT_41A") (portType INOUT))
        (port "29" (symbPinId 29) (portName "VCCPLL") (portType INOUT))
        (port "30" (symbPinId 30) (portName "VCC_2") (portType INOUT))
        (port "31" (symbPinId 31) (portName "IOT_42B") (portType INOUT))
        (port "32" (symbPinId 32) (portName "IOT_43A") (portType INOUT))
        (port "33" (symbPinId 33) (portName "VCCIO_0") (portType INOUT))
        (port "34" (symbPinId 34) (portName "IOT_44B") (portType INOUT))
        (port "35" (symbPinId 35) (portName "IOT_46B_G0") (portType INOUT))
        (port "36" (symbPinId 36) (portName "IOT_48B") (portType INOUT))
        (port "37" (symbPinId 37) (portName "IOT_45A_G1") (portType INOUT))
        (port "38" (symbPinId 38) (portName "IOT_50B") (portType INOUT))
        (port "39" (symbPinId 39) (portName "RGB2") (portType INOUT))
        (port "40" (symbPinId 40) (portName "RGB1") (portType INOUT))
        (port "41" (symbPinId 41) (portName "RGB0") (portType INOUT))
        (port "42" (symbPinId 42) (portName "IOT_51A") (portType INOUT))
        (port "43" (symbPinId 43) (portName "IOT_49A") (portType INOUT))
        (port "44" (symbPinId 44) (portName "IOB_3B_G6") (portType INOUT))
        (port "45" (symbPinId 45) (portName "IOB_5B") (portType INOUT))
        (port "46" (symbPinId 46) (portName "IOB_0A") (portType INOUT))
        (port "47" (symbPinId 47) (portName "IOB_2A") (portType INOUT))
        (port "48" (symbPinId 48) (portName "IOB_4A") (portType INOUT))
        (port "49" (symbPinId 49) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Lattice Semiconductor")
    (property "Manufacturer_Part_Number" "ICE5LP2K-SG48ITR")
    (property "Mouser_Part_Number" "842-ICE5LP2K-SG48ITR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Lattice/ICE5LP2K-SG48ITR?qs=ZwKJWZfDtNgAWzMHJRGDug%3D%3D")
    (property "Arrow_Part_Number" "ICE5LP2K-SG48ITR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ice5lp2k-sg48itr/lattice-semiconductor")
    (property "Description" "FPGA iCE40 Ultra Family 2048 Cells 40nm Technology 1.2V 48-Pin T/R")
    (property "Datasheet_Link" "http://www.latticesemi.com/~/media/LatticeSemi/Documents/DataSheets/iCE/iCE40UltraFamilyDataSheet.pdf")
    (property "symbolName1" "ICE5LP2K-SG48ITR")
)
