(part "TLV75712PDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV75712PDBVR")
    (property "Mouser_Part_Number" "595-TLV75712PDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV75712PDBVR?qs=y6ZabgHbY%252ByWtZe7nf7lPQ%3D%3D")
    (property "Arrow_Part_Number" "TLV75712PDBVR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tlv75712pdbvr/texas-instruments?region=nac")
    (property "Description" "1A Low-Quiescent-Current Low-Dropout (LDO) Regulator")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tlv757p")
    (property "symbolName1" "TLV75712PDBVR")
)
