(part "AT25FF081A-SSHN-B"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "%CS%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SO_(I/O1)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%WP_(I%/O2)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SI_(I/O0)") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SCK") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%HOLD%/%RESET_(I%/O3)") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Renesas Electronics")
    (property "Manufacturer_Part_Number" "AT25FF081A-SSHN-B")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "The AT25FF081A is a member of our Standard class code and data storage solutions and is ideally suited for systems that need fast Read performance and low Sleep power for boot/code shadowing and Execute-in-Place tasks. Its low power consumption and wide operating voltage range are optimized for battery-powered designs.")
    (property "Datasheet_Link" "https://www.renesas.com/us/en/products/memory-logic/non-volatile-memory/spi-nor-flash/dual-quad-spi-memory/at25ff081a-8mbit-165-v-36-v-spi-serial-flash-memory-multi-io-support")
    (property "symbolName1" "AT25FF081A-SSHN-B")
)
